language: objective-c

osx_image: xcode11.3

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BicycleBLEKit.xcodeproj -scheme BicycleBLEKit -sdk iphonesimulator13.2 -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=YES
